### ISSUE TITLE
MiFlora.discover() not returning if devices are already known

### ISSUE THREAD

**Issue by jnooraga** [ChrisScheffler/miflora#5]
I've found an issue in the miflora module where the MiFlora.discover() method will not resolve the open promise if the devices have already been previously discovered. I've verified that adding a new line:

miflora.js
line 162: `return resolve();`

fixes this issue. Please consider adding this fix. Thanks!

**Comment by jnooraga** [comment]
Turns out this causes it to only return one device. Ignore my fix suggestion.

**Comment by ChrisScheffler** [comment]
Could you please check v1.0.6? I might have fixed your issue. As I cannot reproduce your problem I might be wrong.
